Update .travis.yml
Travis has removed `python3`, hence new error with OSX build:
Error: python 2.7.14 is already installed
To upgrade to 3.7.0, run `brew upgrade python`